version: "3.8"
services:
  redis:
    container_name: "scloud_redis"
    image: redis:alpine
    volumes:
      - redis-data:/data
    command:
      - redis-server
    restart: on-failure
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: "scloud_postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scloud
    ports:
      - "5433:5432"
    restart: always

  bot:
    container_name: "scloud_app"
    build: .
    depends_on:
      postgres:
        condition: "service_started"
      redis:
        condition: "service_started"
    env_file:
      - ./.env

    command: sh -c "aerich init -t bot.database.config.TORTOISE_CONFIG --location ./bot/database/migrations &&  aerich init-db && aerich migrate && aerich upgrade && python3 main.py"

volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local
