version: "3.8"
services:
  redis:
    container_name: "SCloud_redis"
    image: redis:alpine
    volumes:
      - redis-data:/data
    command:
      - redis-server
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    container_name: "SCloud_postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always

  bot:
    container_name: "SCloud_app"
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    command: sh -c "aerich init -t bot.database.config.TORTOISE_CONFIG --location ./bot/database/migrations && aerich init-db && aerich migrate && aerich upgrade && python3 main.py"

volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local
