version: "3.8"
services:
  redis:
    container_name: "SCloud_redis"
    image: redis:alpine
    volumes:
      - redis-data:/data
    command:
      - redis-server
    restart: on-failure
    ports:
      - "6380:6379"
  db:
    image: postgres
    container_name: "SCloud_postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: bash -c "until echo 'SELECT 1' | nc -w 1 postgres 5432 > /dev/null 2>&1; do sleep 1; done && aerich upgrade && exec postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always

  bot:
    container_name: "SCloud_app"
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    command: sh -c "aerich init -t bot.database.config.TORTOISE_CONFIG ./bot/database && aerich init-db && aerich migrate && python3 main.py"

volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local
