version: "3.8"
services:
  redis:
    container_name: "scloud_redis"
    image: redis:alpine
    volumes:
      - redis-data:/data
    command:
      - redis-server
    restart: on-failure
    ports:
      - "6380:6379"
  postgres:
    image: postgres:14.2-alpine
    container_name: "scloud_postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=wAsrECUo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scloud
    ports:
      - "5433:5432"
    restart: always

  bot:
    container_name: "scloud_app"
    build: .
    depends_on:
      postgres:
        condition: "service_started"
      redis:
        condition: "service_started"
    env_file:
      - ./.env

    command: sh -c "python3 main.py"

  celery:
    build: .
    container_name: scloud_celery_worker
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
    command: celery -A bot.celery_app worker --concurrency=2 --loglevel=info

  flower:
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis
    command: celery -A bot.celery_app flower --port=5555 --broker=redis://redis:6379/3 --basic_auth=${FLOWER_BASIC_AUTH}
    ports:
      - "5555:5555"

volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local
